# configs/config.yaml

data:
  raw_audio_dir: "data/raw_audio"
  processed_npy_dir: "data/processed_spectrograms"
  metadata_csv: "data/metadata_csv.csv"
  data_csv: "data/birds_voices.csv"
  num_classes: 10
  num_samples_per_class: 50

audio:
  sr: 32000
  n_fft: 2048
  hop_length: 512
  n_mels: 128
  segment_size: 187

model:
    embed_dim: 256
    num_layers: 6
    heads: 8
    patch_size: 25
    forward_expansion: 4
    dropout: 0.1

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.0001
  device: "cuda" # or "cpu", "mps"
